import Header from "./components/Header";
import "./styles.css"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" style={{backgroundColor: '#CDFAFA'}}>
      <body>
        <Header/>
        <br/>
          {children}
      </body>
    </html>
  );
}
